const  data = [
    {
      "id": 7,
      "title": "PHÒNG KHÁCH",
      "icon": "/Content/Uploads/images/danh-muc/icon-phong-khach.png",
      "mateTitle": null,
      "metaKeyword": "nội thất phòng khách giá tốt",
      "metaDescription": "Nội thất phòng khách giá tốt sẽ tiết kiệm chi phí rất lớn dành cho cá nhân, doanh nghiệp đang có nhu cầu làm nội thất. Nội thất tại Xưởng Hoàng Hoan luôn hỗ trợ thiết kế, thi công, bảo hành với dịch vụ tốt nhất để có được những sản phẩm nội thất phòng khách ưng ý.",
      "slug": "phong-khach",
      "orders": 1,
      "parentid": null,
      "createdDate": "2020-08-07T08:43:25.247",
      "updatedDate": "2020-08-07T08:43:25.247",
      "adminCreated": null,
      "adminUpdated": null,
      "notes": null,
      "status": 1,
      "isdelete": null
    },
    {
      "id": 8,
      "title": "PHÒNG NGỦ",
      "icon": "/Content/Uploads/images/danh-muc/icon-phong-ngu.png",
      "mateTitle": null,
      "metaKeyword": "nội thất phòng ngủ",
      "metaDescription": "Xưởng mộc giá tốt cung cấp hơn 200 thiết kế nội thất phòng ngủ với phong cách hiện đại, thi công tại xưởng và bảo hành 1 năm. Với nhiều hạng mục như nội thất phòng ngủ cho bé, nội thất phòng ngủ vợ chồng mới cưới,...",
      "slug": "phong-ngu",
      "orders": 2,
      "parentid": null,
      "createdDate": "2020-08-07T00:00:00",
      "updatedDate": "2020-08-07T00:00:00",
      "adminCreated": null,
      "adminUpdated": null,
      "notes": null,
      "status": 1,
      "isdelete": null
    },
    {
      "id": 10,
      "title": "PHÒNG BẾP",
      "icon": "/Content/Uploads/images/danh-muc/icon-phong-bep.png",
      "mateTitle": null,
      "metaKeyword": "nội thất phòng bếp",
      "metaDescription": "Nội thất phòng bếp rất quan trọng trong toàn bộ ngôi nhà, xưởng mộc giá tốt chuyên cung cấp các hạng mục sản phẩm nội thất phòng bếp với giá tốt nhất từ khâu thiết kế, thi công, bảo hành toàn quốc.",
      "slug": "phong-bep",
      "orders": 3,
      "parentid": null,
      "createdDate": "2020-08-07T08:49:01.417",
      "updatedDate": "2020-08-07T08:49:01.417",
      "adminCreated": null,
      "adminUpdated": null,
      "notes": null,
      "status": 1,
      "isdelete": null
    },
    {
      "id": 11,
      "title": "PHÒNG TẮM",
      "icon": "/Content/Uploads/images/danh-muc/icon-phong-tam.png",
      "mateTitle": null,
      "metaKeyword": "nội thất phòng tắm",
      "metaDescription": "Xưởng Mộc giá tốt chuyên cung cấp nội thất phòng tắm với chất liệu gỗ cao cấp được nhập khẩu trực tiếp từ nhiều nước, hơn 200 mẫu thiết kế nội thất phòng tắm giúp khách hàng dễ dàng lựa chọn sản phẩm phù hợp trên toàn quốc.",
      "slug": "phong-tam",
      "orders": 4,
      "parentid": null,
      "createdDate": "2020-08-07T08:51:47.123",
      "updatedDate": "2020-08-07T08:51:47.123",
      "adminCreated": null,
      "adminUpdated": null,
      "notes": null,
      "status": 1,
      "isdelete": null
    },
    {
      "id": 12,
      "title": "TRẺ EM",
      "icon": "/Content/Uploads/images/danh-muc/icon-tre-em.png",
      "mateTitle": null,
      "metaKeyword": "đồ chơi trẻ em bằng gỗ",
      "metaDescription": "xưởng mộc giá tốt chuyên cung cấp đồ chơi trẻ em bằng gỗ với chất lượng cao cấp, an toàn cho bé. Hơn 20 năm sản xuất các sản phẩm nội thất cho bé, chúng tôi cam kết những sản phẩm đồ chơi gỗ tốt nhất thị trường.",
      "slug": "tre-em",
      "orders": 5,
      "parentid": null,
      "createdDate": "2020-08-07T09:00:12.947",
      "updatedDate": "2020-08-07T09:00:12.947",
      "adminCreated": null,
      "adminUpdated": null,
      "notes": null,
      "status": 1,
      "isdelete": null
    },
    {
      "id": 13,
      "title": "VĂN PHÒNG",
      "icon": "/Content/Uploads/images/danh-muc/icon-van-phong.png",
      "mateTitle": null,
      "metaKeyword": "nội thất văn phòng",
      "metaDescription": "Nội thất văn phòng Hoàng Hoan sản xuất trực tiếp tại xưởng với hơn 20 năm kinh nghiệm và nhiều đối tác lớn, chúng tôi tự tin đem lại những sản phẩm nội thất văn phòng đẹp, bền, tiết kiệm nhất.",
      "slug": "van-phong",
      "orders": 6,
      "parentid": null,
      "createdDate": "2020-08-07T09:02:18.78",
      "updatedDate": "2020-08-07T09:02:18.78",
      "adminCreated": null,
      "adminUpdated": null,
      "notes": null,
      "status": 1,
      "isdelete": null
    },
    {
      "id": 14,
      "title": "CẦU THANG",
      "icon": "/Content/Uploads/images/danh-muc/icon-cau-thang.png",
      "mateTitle": null,
      "metaKeyword": "thi công cầu thang gỗ",
      "metaDescription": "Xưởng mộc Hoàng Hoan chuyên thi công cầu thang gỗ với chi phí tốt nhất. Với hơn 200 mẫu cầu thang gỗ bắt mắt, chúng tôi sẽ đem lại không gian tuyệt vời cho ngôi nhà của bạn.",
      "slug": "cau-thang",
      "orders": 7,
      "parentid": null,
      "createdDate": "2020-08-07T09:04:36.937",
      "updatedDate": "2020-08-07T09:04:36.937",
      "adminCreated": null,
      "adminUpdated": null,
      "notes": null,
      "status": 1,
      "isdelete": null
    },
    {
      "id": 15,
      "title": "TRANG TRÍ",
      "icon": "/Content/Uploads/images/danh-muc/icon-do-trang-tri.png",
      "mateTitle": null,
      "metaKeyword": "nội thất trang trí",
      "metaDescription": "Xưởng mộc hoàng hoan chuyên thi công nội thất trang trí với hơn 2000 mẫu mã sản phẩm thiết kế đa dạng. Được sản xuất trực tiếp tại xưởng các sản phẩm nội thất trang trí sẽ được bảo hành 1 năm và chi phí rẻ nhất.",
      "slug": "trang-tri",
      "orders": 8,
      "parentid": null,
      "createdDate": "2020-08-07T09:06:19.113",
      "updatedDate": "2020-08-07T09:06:19.113",
      "adminCreated": null,
      "adminUpdated": null,
      "notes": null,
      "status": 1,
      "isdelete": null
    }
  ]

  export default data;