export const LIST_PRODUCT ="LIST_PRODUCT"
export const BUY_ITEM ="BUY_ITEM"
export const UPDATE_ITEM ="UPDATE_ITEM"
export const DELETE_ITEM ="DELETE_ITEM"
export const CHANGE_NOTIFY ="CHANGE_NOTIFY"
